resources:
 - name: cypress-example-kitchensink
   type: git
   source: &repo-source
     uri: https://github.com/Lebedinskiy/cypress-example-kitchensink
     branch: master
 - name: dependency-cache
   type: npm-cache
   source:
     <<: *repo-source
     paths:
       - package.json

jobs:
 - name: Install dependencies
   plan:
     - get: cypress-example-kitchensink
       trigger: true
     - get: dependency-cache
     - name: Run tests
 - name: check dependencies    
   plan:
     - get: cypress-example-kitchensink
       trigger: true
       passed: [Install dependencies]
     - get: dependency-cache
       passed: [Install dependencies]
     - task: run the test suite
       file: cypress-example-kitchensink/yuriypipeline.yml
