jobs:
 - name: Build
   serial: true
   plan:
     - get: my_repo
       trigger: true
     - task: build-project
       config:
         platform: linux
         image_resource:
           type: docker-image
           source: {repository: "cypress/base", tag: "10"}
         inputs:
         - name: my_repo
         outputs:
         - name: workspace
         run:
           path: /bin/sh
           args:
           - -c
           - |
             output_dir=workspace

             node --version
             npm --version

             cat << EOF > "${output_dir}/Dockerfile"
             FROM cypress/base:10
             RUN node --version
             RUN npm --version
             WORKDIR /home/node/app
             COPY package.json package-lock.json ./
             COPY app ./app
             COPY serve.json ./
             COPY cypress.json cypress ./
             COPY cypress ./cypress
             ENV CI=1
             RUN npm ci
             EOF

             cp -R ./my_repo/package.json "${output_dir}"
             cp -R ./my_repo/app "${output_dir}"
             cp -R ./my_repo/serve.json "${output_dir}"
             cp -R ./my_repo/cypress.json "${output_dir}"
             cp -R ./my_repo/cypress "${output_dir}"
             cp -R ./my_repo/package-lock.json "${output_dir}"
             cd workspace
             ls -la

     - put: ecr
       params: 
         build: workspace

 - name: test
   plan:
   - get: ecr
     passed: [Build]
     trigger: true
   - get: my_repo
     passed: [Build]
   - task: run-tests
     image: ecr
     config:
       platform: linux
       inputs:
       - name: my_repo
       run:
         dir: my_repo
         path: sh
         args:
         - -c
         - |
           node --version
           npm --version

 - name: Deploy-to-prod
   plan:
   - get: ecr
     passed: [test]
     trigger: true
   - put: Prod
     params:
       save: /home/ubuntu/image
       save: true
   - task: push-to-prod
     image: ecr
     config:
       platform: linux
       inputs:
       - name: Prod
       run:
         path: sh
         args:
         - -exc
         - |

           ls Prod
           docker-images


resources:
 - name: my_repo
   type: git
   source:
     uri: https://github.com/Lebedinskiy/cypress-example-kitchensink.git
     branch: master

 - name: ecr
   type: docker-image
   source:
     repository: 790135736964.dkr.ecr.eu-central-1.amazonaws.com/second
     access_key_id: ((AWS_ACCESS_KEY))
     secret_access_key: ((AWS_SECRET_KEY))
     region_name: ((AWS_REGION))

 - name: Prod
   type: docker-image
   source:
     host: 18.156.192.252
     user: ubuntu
     private_key: ((private_key))
