jobs:
 - name: Build
   plan:
     - get: my_repo
       trigger: true
     - task: build-code
       config:
         platform: linux
         image_resource:
           type: docker-image
           source: 
             repository: docker
         inputs:
         - name: my_repo
         outputs:
         - name: workspace
         params:
           DOCKERFILE: my_repo/Dockerfile
           CONTEXT: .

         run:
           path: build


 - name: Test
   plan:
     - get: my_repo
       trigger: true
     - task: test-code
       config:
         platform: linux
         image_resource:
           type: docker-image
           source:
             repository: docker
         inputs:
         - name: my_repo
         outputs:
         - name: workspace
         run:
           path: /bin/sh
           args:
           - -c
           - |
             cd my_repo
             ls -la
             docker -v
             docker images
             whoami
             docker ps -a
             cp -R ./my-repo my-repo/workspace
resources:
 - name: my_repo
   type: git
   source:
     uri: https://github.com/Lebedinskiy/cypress-example-kitchensink.git
     branch: master
