jobs:
 - name: Deploy
   plan:
     - get: my_repo
       trigger: true
     - task: build-code
       config:
         platform: linux
         image_resource:
           type: docker-image
           source:
             repository: ubuntu
         inputs:
         - name: my_repo
         outputs:
         - name: workspace
         run:
           path: /bin/bash
           args:
             - -c
             - |
               echo "Hi"
               uname
               ls -la
               cd my_repo
               ls -la
               docker -v
               docker build .
resources:
 - name: my_repo
   type: git
   source:
     uri: https://github.com/Lebedinskiy/cypress-example-kitchensink.git
     branch: master