jobs:
 - name: Deploy
   plan:
     - get: my_repo
       trigger: true
     - task: build-code
       file: cypress-example-kitchensink/Dockerfile
resources:
 - name: my_repo
   type: git
   source:
     uri: git@github.com:Lebedinskiy/cypress-example-kitchensink.git
     branch: master
     paths: [Dockerfile]
