jobs:
 - name: test-image
   plan:
   - get: yuriy-dockerhub
     passed: [Test]
     trigger: true
   - get: my_repo
     passed: [Test]
   - task: run-tests
     image: yuriy-dockerhub
     config:
       platform: linux
       inputs:
       - name: my_repo
       run:
         dir: my_repo
         path: sh
         args:
         - exec
         - rspec
         - --help

 - name: Build
   public: true
   serial: true
   plan:
     - get: my_repo
       trigger: true
     - task: build-project
       config:
         platform: linux
         image_resource:
           type: docker-image
           source: {repository: "cypress/base", tag: "10"}
         inputs:
         - name: my_repo
         outputs:
         - name: ci
         run:
           path: /bin/sh
           args:
           - -c
           - |
             output_dir=ci

             node --version
             npm --version

             cat << EOF > "${output_dir}/Dockerfile"
             FROM cypress/base:10
             RUN node --version
             RUN npm --version
             WORKDIR /home/node/app
             COPY package.json package-lock.json ./
             COPY app ./app
             COPY serve.json ./
             COPY cypress.json cypress ./
             COPY cypress ./cypress
             ENV CI=1
             RUN npm ci
             RUN $(npm bin)/cypress verify
             EOF

             cp -R ./my_repo/package.json "${output_dir}"
             cp -R ./my_repo/app "${output_dir}"
             cp -R ./my_repo/serve.json "${output_dir}"
             cp -R ./my_repo/cypress.json "${output_dir}"
             cp -R ./my_repo/cypress "${output_dir}"
             cp -R ./my_repo/package-lock.json "${output_dir}"
             cd ci
             ls -la

     - put: ecr
       params: { build: ci }

 - name: test
   plan:
   - get: ecr
     passed: [Build]
     trigger: true
   - get: my-repo
     passed: [Build]
   - task: run-tests
     image: ecr
     config:
       platform: linux
       inputs:
       - name: my-repo
       run:
         dir: my-repo
         path: sh
         args:
         - node --version
         - npm --version


resources:
 - name: my_repo
   type: git
   source:
     uri: https://github.com/Lebedinskiy/cypress-example-kitchensink.git
     branch: master

 - name: ecr
   type: docker-image
   source:
     repository: 790135736964.dkr.ecr.eu-central-1.amazonaws.com/concourse
     access_key_id: {{AWS_ACCESS_KEY_ID}}
     secret_access_key: {{AWS_SECRET_ACCESS_KEY}}