jobs:
 - name: Deploy
   serial: true
   public: true
   plan:
     - get: my_repo
       trigger: true
     - task: build-code
       file: cypress-example-kitchensink/ci/build.yml
resources:
 - name: my_repo
   type: git
   source:
     uri: https://github.com/Lebedinskiy/cypress-example-kitchensink.git
     branch: master
     paths: [cypress-example-kitchensink/]
